# Generated by Django 3.0.8 on 2021-02-05 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_journalentry_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='filePath',
            field=models.FileField(upload_to='%Y/%m/%d/'),
        ),
    ]
